---
- name: This playbook manages creation and scheduling of reports in Cisco Catalyst Center
  hosts: catalyst_center_hosts
  connection: local
  gather_facts: no

  vars_files:
    - "{{ VARS_FILE_PATH }}"

  vars:
    state: merged
    
    # Define the default values for the Catalyst Center login in inventory file under host. Refer the host.yml file for more details
    catalyst_center_login: &catalyst_center_login
      dnac_host: "{{ catalyst_center_host | default(dnac_host) }}"
      dnac_username: "{{ catalyst_center_username | default(dnac_username) }}"
      dnac_password: "{{ catalyst_center_password | default(dnac_password) }}"
      dnac_version: "{{ catalyst_center_version | default(dnac_version) }}"
      dnac_port: "{{ catalyst_center_port | default(443) }}"
      dnac_verify: "{{ catalyst_center_verify | default(dnac_verify) }}"
      config_verify: "{{ catalyst_center_config_verify | default(False) }}"
      dnac_debug: "{{ catalyst_center_debug | default(False) }}"
      dnac_log: "{{ catalyst_center_log | default(False) }}"
      dnac_log_level: "{{ catalyst_center_log_level | default('INFO') }}"
      dnac_log_file_path: "{{ catalyst_center_log_file_path | default(omit) }}"
      dnac_log_append: "{{ catalyst_center_log_append | default(False) }}"
      dnac_api_task_timeout: "{{ catalyst_center_api_task_timeout | default(1200) }}"
      
  tasks:
    - name: Print input file path
      debug:
        msg: "Input file selected: {{ VARS_FILE_PATH }}"
    
    - name: Reports playbook start time
      set_fact:
        long_op_start: "{{ now() }}"

    - name: Create or schedule reports provided in reports_config in file {{ VARS_FILE_PATH }}
      cisco.dnac.reports_workflow_manager:
        <<: *catalyst_center_login
        state: "{{ state }}"
        config: "{{ reports_config }}"
      when: reports_config is defined
      register: reports_output

    - name: Print reports workflow output
      debug:
        var: reports_output
      when: reports_output is defined

    - name: Reports playbook end time
      set_fact:
        long_op_end: "{{ now() }}"
    
    - name: Print Reports playbook execution time
      debug:
        msg: "Reports playbook - Start: {{ long_op_start }}, End: {{ long_op_end }}"

  post_tasks:
    - name: Get python version
      ansible.builtin.command: which python
      register: ansible_play_path
      delegate_to: catalyst_center_hosts
      connection: local
      changed_when: false