---
- name: Delete Access Point Locations from Cisco Catalyst Center
  hosts: catalyst_center_hosts
  connection: local
  gather_facts: no

  vars_files:
    - "{{ VARS_FILE_PATH }}"

  vars:
    state: deleted
    
    catalyst_center_login: &catalyst_center_login
      dnac_host: "{{ catalyst_center_host | default(dnac_host) }}"
      dnac_username: "{{ catalyst_center_username | default(dnac_username) }}"
      dnac_password: "{{ catalyst_center_password | default(dnac_password) }}"
      dnac_version: "{{ catalyst_center_version | default(dnac_version) }}"
      dnac_port: "{{ catalyst_center_port | default(443) }}"
      dnac_verify: "{{ catalyst_center_verify | default(dnac_verify) }}"
      config_verify: "{{ catalyst_center_config_verify | default(False) }}"
      dnac_debug: "{{ catalyst_center_debug | default(False) }}"
      dnac_log: "{{ catalyst_center_log | default(False) }}"
      dnac_log_level: "{{ catalyst_center_log_level | default('INFO') }}"
      dnac_log_file_path: "{{ catalyst_center_log_file_path | default(omit) }}"
      dnac_log_append: "{{ catalyst_center_log_append | default(False) }}"
      dnac_api_task_timeout: "{{ catalyst_center_api_task_timeout | default(1200) }}"
      
  tasks:
    - name: Print input file path
      debug:
        msg: "Input file selected: {{ VARS_FILE_PATH }}"
    
    - name: Delete Access Point Location playbook start time
      set_fact:
        long_op_start: "{{ now() }}"

    - name: Delete Access Point Locations provided in accesspoint_location_details in file {{ VARS_FILE_PATH }}
      cisco.dnac.accesspoint_location_workflow_manager:
        <<: *catalyst_center_login
        state: "{{ state }}"
        config: "{{ accesspoint_location_details }}"
      when: accesspoint_location_details is defined
      register: delete_accesspoint_location_output

    - name: Print Delete Access Point Location workflow output
      debug:
        var: delete_accesspoint_location_output
      when: delete_accesspoint_location_output is defined

    - name: Delete Access Point Location playbook end time
      set_fact:
        long_op_end: "{{ now() }}"
    
    - name: Print Delete Access Point Location playbook execution time
      debug:
        msg: "Delete Access Point Location playbook - Start: {{ long_op_start }}, End: {{ long_op_end }}"

  post_tasks:
    - name: Get python version
      ansible.builtin.command: which python
      register: ansible_play_path
      delegate_to: catalyst_center_hosts
      connection: local
      changed_when: false