---
catalyst_center_version: 2.3.7.6
accesspoints_details:
  - mac_address: a4:88:73:d0:53:60
    ap_mode: Local
    2.4ghz_radio:
      admin_status: "Enabled"
      antenna_name: "AIR-ANT2513P4M-N-2.4GHz"
      radio_role_assignment: Client-Serving
      power_level: 5
      channel_number: 5
  - mac_address: 90:e9:5e:03:f3:41
    2.4ghz_radio:
      admin_status: "Enabled"
      power_assignment_mode: "Global"
  - mac_address: 90:e9:5e:03:f3:42
    2.4ghz_radio:
      admin_status: "Enabled"
      channel_assignment_mode: "Global"
  - mac_address: 90:e9:5e:03:f3:40
    5ghz_radio:
      admin_status: "Enabled"
      antenna_name: "AIR-ANT2513P4M-N-5GHz"
  - mac_address: 90:e9:5e:03:f3:40
    5ghz_radio:
      admin_status: "Enabled"
      antenna_name: "AIR-ANT2513P4M-N-5GHz"
      radio_role_assignment: "Client-Serving"
      channel_number: 44
  - mac_address: 90:e9:5e:03:f3:40
    5ghz_radio:
      admin_status: "Enabled"
      antenna_name: "C-ANT9104-Single-D0-5GHz"
      channel_number: 52
      power_level: 5
      channel_width: "40 MHz"
  - mac_address: 90:e9:5e:03:f3:40
    2.4ghz_radio:
      admin_status: "Enabled"
      antenna_name: "C-ANT9103-2.4GHz"
      channel_number: 9
      power_level: 4
    5ghz_radio:
      admin_status: "Enabled"
      antenna_name: "C-ANT9103-5GHz"
      channel_number: 40
      power_level: 3
      channel_width: "20 MHz"
  - mac_address:  90:e9:5e:03:f3:40
    rf_profile: "HIGH"
    site:
      floor:
        name: "FLOOR1"
        parent_name: "Global/USA/New York/BLDNYC"
  - mac_address: a4:88:73:d4:d6:60
    ap_name: "Cisco_Test_AP_T003"
    admin_status: "Enabled"
    led_status: "Enabled"
    led_brightness_level: 1
    ap_mode: "Local"
    is_assigned_site_as_location: "Enabled"
    failover_priority: "Low"
    primary_controller_name: "NY-EWLC-1"
    primary_ip_address:
      address: "204.192.6.200"
    secondary_controller_name: "NY-EWLC-20"
    secondary_ip_address:
      address: "fe80::202:b3ff:fe1e:8324"
    tertiary_controller_name: "SJ-EWLC-20"
    tertiary_ip_address:
      address: "fe80::202:b3ff:fe1e:8325"
  - mac_address: a4:88:73:d4:d6:60
    ap_name: "Cisco_Test_AP_T003"
    admin_status: "Enabled"
    led_status: "Enabled"
    led_brightness_level: 1
    ap_mode: "Local"
    is_assigned_site_as_location: "Enabled"
    failover_priority: "Low"
    primary_controller_name: "NY-EWLC-10"
    primary_ip_address:
      address: "fe80::202:b3ff:fe1e:8329"
    secondary_controller_name: "NY-EWLC-20"
    secondary_ip_address:
      address: "fe80::202:b3ff:fe1e:8324"
    tertiary_controller_name: "Inherit from site / Clear"
  
  - mac_address: 90:e9:5e:03:f3:40
    rf_profile: "HIGH"
    site:
      floor:
        name: "FLOOR1"
        parent_name: "Global/USA/New York/BLDNYC"
    ap_name: "LTTS-test2"
    admin_status: "Enabled"
    led_status: "Enabled"
    led_brightness_level: 5
    ap_mode: "Local"
    is_assigned_site_as_location: "Enabled"
    failover_priority: "Low"
    2.4ghz_radio:
      admin_status: "Enabled"
      antenna_name: "C-ANT9104-2.4GHz"
      radio_role_assignment: "Client-Serving"
      channel_number: 5
      power_level: 2
    5ghz_radio:
      admin_status: "Enabled"
      antenna_name: "AIR-ANT2513P4M-N-5GHz"
      radio_role_assignment: "Client-Serving"
      channel_number: 36
      power_level: 2
      channel_width: "40 MHz"
  - mac_address: 6c:d6:e3:75:5a:e0
    ap_name: "LTTS_Test_9120_T2"
    admin_status: "Enabled"
    led_status: "Enabled"
    led_brightness_level: 2
    ap_mode: "Local"
    is_assigned_site_as_location: "Enabled"
    failover_priority: "Low"
    primary_controller_name: "NY-IAC-EWLC.cisco.local"
    primary_ip_address:
      address: "204.192.6.200"
    secondary_controller_name: "Inherit from site / Clear"
    tertiary_controller_name: "Inherit from site / Clear"
    xor_radio:
      admin_status: "Enabled"
      radio_role_assignment: "Client-Serving"
      channel_number: 4
      radio_band: "2.4 GHz"
      channel_width: "40 MHz"
    5ghz_radio:
      admin_status: "Enabled"
      antenna_name: "AIR-ANT2513P4M-N-5GHz"
      radio_role_assignment: "Client-Serving"
      channel_number: 40
      power_level: 2
      channel_width: "80 MHz"
  - mac_address: e4:38:7e:42:bc:00
    ap_name: "LTTS_Test_9166_T3"
    admin_status: "Enabled"
    led_status: "Enabled"
    led_brightness_level: 3
    ap_mode: "Local"
    is_assigned_site_as_location: "Enabled"
    failover_priority: "Low"
    primary_controller_name: "NY-IAC-EWLC"
    primary_ip_address:
      address: "204.192.6.200"
    secondary_controller_name: "Inherit from site / Clear"
    tertiary_controller_name: "Inherit from site / Clear"
    2.4ghz_radio:
      admin_status: "Enabled"
      radio_role_assignment: "Client-Serving"
      channel_number: 3
      power_level: 3
    5ghz_radio:
      admin_status: "Enabled"
      radio_role_assignment: "Client-Serving"
      channel_number: 44
      power_level: 3
      channel_width: "20 MHz"
    xor_radio:
      admin_status: "Enabled"
      radio_role_assignment: "Client-Serving"
      channel_number: 1
      power_level: 3
      radio_band: "6 GHz"
      channel_width: "40 MHz"
  
  - mac_address: 90:e9:5e:03:f3:40
    2.4ghz_radio:
      admin_status: "Enabled"
      antenna_name: "AIR-ANT2513P4M-N-2.4GHz"
      radio_role_assignment: "Client-Serving"
      power_level: 5
      channel_number: 7
  - mac_address: 90:e9:5e:03:f3:40
    2.4ghz_radio:
      admin_status: "Enabled"
      power_assignment_mode: "Global"
  - mac_address: 90:e9:5e:03:f3:40
    2.4ghz_radio:
      admin_status: "Enabled"
      channel_assignment_mode: "Global"
  - mac_address: 90:e9:5e:03:f3:40
    5ghz_radio:
      admin_status: "Enabled"
      antenna_name: "AIR-ANT2513P4M-N-5GHz"
  - mac_address: 90:e9:5e:03:f3:40
    5ghz_radio:
      admin_status: "Enabled"
      antenna_name: "AIR-ANT2513P4M-N-5GHz"
      radio_role_assignment: "Client-Serving"
      channel_number: 44
  - mac_address: 90:e9:5e:03:f3:40
    5ghz_radio:
      admin_status: "Enabled"
      antenna_name: "C-ANT9104-Single-D0-5GHz"
      channel_number: 52
      power_level: 5
      channel_width: "40 MHz"
  - mac_address: 90:e9:5e:03:f3:40
    2.4ghz_radio:
      admin_status: "Enabled"
      antenna_name: "C-ANT9103-2.4GHz"
      channel_number: 9
      power_level: 4
    5ghz_radio:
      admin_status: "Enabled"
      antenna_name: "C-ANT9103-5GHz"
      channel_number: 40
      power_level: 3
      channel_width: "20 MHz"
  - mac_address: 90:e9:5e:03:f3:40
    rf_profile: "HIGH"
    site:
      floor:
        name: "FLOOR1"
        parent_name: "Global/USA/New York/BLDNYC"
  - mac_address: a4:88:73:d4:d6:60
    ap_name: "Cisco_Test_AP_T003"
    admin_status: "Enabled"
    led_status: "Enabled"
    led_brightness_level: 1
    ap_mode: "Local"
    is_assigned_site_as_location: "Enabled"
    failover_priority: "Low"
    primary_controller_name: "NY-EWLC-1"
    primary_ip_address:
      address: "204.192.6.200"
    secondary_controller_name: "NY-EWLC-20"
    secondary_ip_address:
      address: "fe80::202:b3ff:fe1e:8324"
    tertiary_controller_name: "SJ-EWLC-20"
    tertiary_ip_address:
      address: "fe80::202:b3ff:fe1e:8325"
  - mac_address: a4:88:73:d4:d6:60
    ap_name: "Cisco_Test_AP_T003"
    admin_status: "Enabled"
    led_status: "Enabled"
    led_brightness_level: 1
    ap_mode: "Local"
    is_assigned_site_as_location: "Enabled"
    failover_priority: "Low"
    primary_controller_name: "NY-EWLC-10"
    primary_ip_address:
      address: "fe80::202:b3ff:fe1e:8329"
    secondary_controller_name: "NY-EWLC-20"
    secondary_ip_address:
      address: "fe80::202:b3ff:fe1e:8324"
    tertiary_controller_name: "Inherit from site / Clear"
  - mac_address: 90:e9:5e:03:f3:40
    rf_profile: "HIGH"
    site:
      floor:
        name: "FLOOR1"
        parent_name: "Global/USA/New York/BLDNYC"
    ap_name: "LTTS-test2"
    admin_status: "Enabled"
    led_status: "Enabled"
    led_brightness_level: 5
    ap_mode: "Local"
    is_assigned_site_as_location: "Enabled"
    failover_priority: "Low"
    2.4ghz_radio:
      admin_status: "Enabled"
      antenna_name: "C-ANT9104-2.4GHz"
      radio_role_assignment: "Client-Serving"
      channel_number: 5
      power_level: 2
    5ghz_radio:
      admin_status: "Enabled"
      antenna_name: "AIR-ANT2513P4M-N-5GHz"
      radio_role_assignment: "Client-Serving"
      channel_number: 36
      power_level: 2
      channel_width: "40 MHz"
  - mac_address: 6c:d6:e3:75:5a:e0
    ap_name: "LTTS_Test_9120_T2"
    admin_status: "Enabled"
    led_status: "Enabled"
    led_brightness_level: 2
    ap_mode: "Local"
    is_assigned_site_as_location: "Enabled"
    failover_priority: "Low"
    primary_controller_name: "NY-IAC-EWLC.cisco.local"
    primary_ip_address:
      address: "204.192.6.200"
    secondary_controller_name: "Inherit from site / Clear"
    tertiary_controller_name: "Inherit from site / Clear"
    xor_radio:
      admin_status: "Enabled"
      radio_role_assignment: "Client-Serving"
      channel_number: 4
      radio_band: "2.4 GHz"
      channel_width: "40 MHz"
    5ghz_radio:
      admin_status: "Enabled"
      antenna_name: "AIR-ANT2513P4M-N-5GHz"
      radio_role_assignment: "Client-Serving"
      channel_number: 40
      power_level: 2
      channel_width: "80 MHz"
  - mac_address: e4:38:7e:42:bc:00
    ap_name: "LTTS_Test_9166_T3"
    admin_status: "Enabled"
    led_status: "Enabled"
    led_brightness_level: 3
    ap_mode: "Local"
    is_assigned_site_as_location: "Enabled"
    failover_priority: "Low"
    primary_controller_name: "NY-IAC-EWLC"
    primary_ip_address:
      address: "204.192.6.200"
    secondary_controller_name: "Inherit from site / Clear"
    tertiary_controller_name: "Inherit from site / Clear"
    2.4ghz_radio:
      admin_status: "Enabled"
      radio_role_assignment: "Client-Serving"
      channel_number: 3
      power_level: 3
    5ghz_radio:
      admin_status: "Enabled"
      radio_role_assignment: "Client-Serving"
      channel_number: 44
      power_level: 3
      channel_width: "20 MHz"
    xor_radio:
      admin_status: "Enabled"
      radio_role_assignment: "Client-Serving"
      channel_number: 1
      power_level: 3
      radio_band: "6 GHz"
      channel_width: "40 MHz"
  - reboot_aps:
      mac_addresses:
        - "6c:d6:e3:75:5a:e0"
        - "e4:38:7e:42:bc:00"
  - reboot_aps:
      hostnames:
        - "cisco_Test_9166_T3"
        - "cisco_Test_9120_T1"
  - factory_reset_aps:
      mac_addresses:
        - "6c:d6:e3:75:5a:e0"
        - "e4:38:7e:42:bc:00"
  - bulk_update_aps:
      ap_identifier:
        - mac_address: e4:38:7e:42:bc:40
          ap_name: "Cisco_9166_T2"
        - mac_address: a4:88:73:d0:53:60
          ap_name: "Cisco_9120_T2"
      common_fields_to_change:
        admin_status: "Disabled"
        led_status: "Enabled"
        led_brightness_level: 1
        ap_mode: "Local"
        is_assigned_site_as_location: "Enabled"
        failover_priority: "Low"
        clean_air_si_2.4ghz: "Enabled"
        clean_air_si_5ghz: "Enabled"
        clean_air_si_6ghz: "Disabled"
        primary_controller_name: "SJ-EWLC-1"
        primary_ip_address:
          address: "204.192.4.200"
        secondary_controller_name: "Inherit from site / Clear"
        tertiary_controller_name: "Inherit from site / Clear"

  - mac_address: 2c:e3:8e:af:d2:e0
    ap_name: Test_AP1
    admin_status: Enabled
    led_status: Enabled
    led_brightness_level: 7
    ap_mode: Local
    site:
      floor:
        name: FLOOR4
        parent_name: "Global/USA/SAN JOSE/SJ_BLD23"
    is_assigned_site_as_location: Enabled
    failover_priority: Low
    clean_air_si_2.4ghz: Enabled
    clean_air_si_5ghz: Enabled
    clean_air_si_6ghz: Enabled
    rf_profile: HIGH
    primary_controller_name: SJ-EWLC-1
    primary_ip_address:
      address: 204.192.4.200
    secondary_controller_name: NY-EWLC-1
    secondary_ip_address:
      address: 204.192.6.200
    tertiary_controller_name: "Inherit from site / Clear"

  - mac_address: 2c:e3:8e:af:d2:e0
    admin_status: Enabled
    ap_mode: Local
    6ghz_radio:
      admin_status: Enabled
      radio_role_assignment: "Client-Serving"
      power_assignment_mode: "Global"
      channel_assignment_mode: "Global"
      channel_number: 13

  - mac_address: 14:16:9d:2e:a5:60
    admin_status: Enabled
    ap_mode: Local
    2.4ghz_radio:
      admin_status: "Enabled"
      radio_role_assignment: "Client-Serving"
      channel_assignment_mode: "Custom"
      channel_number: 5

  - mac_address: e4:38:7e:42:ee:80
    admin_status: Enabled
    ap_mode: Local
    5ghz_radio:
      admin_status: "Enabled"
      radio_role_assignment: "Client-Serving"
      channel_assignment_mode: "Custom"
      channel_number: 56

  - mac_address: a4:88:73:d0:53:60
    rf_profile: "HIGH"
    site:
      floor :
        name: FLOOR1
        parent_name: "Global/USA/SAN JOSE/SJ_BLD23"